name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
        - uses: actions/checkout@v4
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        - run: docker build . -t testapp:v1
        # - run: docker scout quickview testapp:v1
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              push: true
              tags: abhilashshettigar/testapp:v1